package pricing

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sync"
)

// snapshot.json is generated by `make catalog` from models.dev. It is checked
// in so a build is reproducible and an offline install still has prices on the
// first request, before anyone has pressed refresh.
//
//go:embed snapshot.json
var snapshotJSON []byte

var (
	embeddedOnce sync.Once
	embedded     *Snapshot
	embeddedErr  error
)

// Embedded returns the catalog compiled into this binary.
func Embedded() (*Snapshot, error) {
	embeddedOnce.Do(func() {
		var s Snapshot
		if err := json.Unmarshal(snapshotJSON, &s); err != nil {
			embeddedErr = fmt.Errorf("read embedded price catalog: %w", err)
			return
		}
		embedded = &s
	})
	return embedded, embeddedErr
}
